# Name of your application. Used to uniquely configure containers.
service: kamal-eagertalk

# Name of the container image.
image: kamal-eagertalk

# Deploy to these servers.
servers:
  web:
    - <your-server-ip>

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
proxy:
  ssl: true
  host: <your-domain>

# Credentials for your image host.
registry:
  server: <account-id>.dkr.ecr.<region>.amazonaws.com
  username: AWS
  # Assumes default profile
  password: <%= %x(aws ecr get-login-password) %>

# Configure builder setup.
builder:
  arch: amd64
  # Pass in additional build args needed for your Dockerfile.
  # args:

# Inject ENV variables into containers (secrets come from .kamal/secrets).
#
env:
  clear:
    DB_HOST: 192.168.0.2

# Use a different ssh user than root
#
ssh:
  user: ubuntu
